export default {
  use24h: false,
  showAmpm: true,
  showWeekday: true,
  showAffirmations: true,
  useMetricDistance: false,
  useMetricEnergy: false,
  name: null,
  showHr: true,
  showStatsCardBg: true,
  card0Stat: "steps",
  card1Stat: "distance",
  card2Stat: "calories",
  ring0Stat: "steps",
  ring1Stat: "distance",
  ring2Stat: "calories",
};